
server.port=8080


#Spring Data JPA
spring.datasource.url=jdbc:postgresql://dpg-d8u4gsmrnols73f10acg-a:5432/proyecto_play_db
spring.datasource.username=torrice
spring.datasource.password=8eZz5VsWvwoTGzYb7eQTgbQKSKymHvkr

spring.sql.init.mode=ALWAYS


spring.jpa.hibernate.ddl-auto=update
#LangChain4j
langchain4j.open-ai.chat-model.api-key=demo

